/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * The Spice Kitchen - Digital Restaurant Menu Database (Pure Vanilla JS)
 */

export const RESTAURANTS = {
  'spice-kitchen': {
    id: 'spice-kitchen',
    name: 'The Spice Kitchen',
    tagline: 'Authentic Indian Cuisine & Clay Tandoor',
    cuisine: 'North Indian · Awadhi · Mughlai · Tandoori',
    address: '100 Feet Road, Indiranagar, Bengaluru, Karnataka 560038',
    phone: '+91 80 4123 9876',
    openHours: '12:00 PM – 11:30 PM (Daily)',
    status: 'Open Now · Closes 11:30 PM',
    rating: 4.8,
    reviewCount: 1420,
    coverImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&auto=format&fit=crop&q=80',
    logo: '🍽️',
    themeColor: '#8B1E1E',
    accentColor: '#D97706',
    tableDefault: 'Table 04',
    fssaiNumber: '11223344556677',
    wifiName: 'SpiceKitchen_Guest',
    wifiPass: 'currylover2026'
  },
  'royal-biryani': {
    id: 'royal-biryani',
    name: 'Royal Biryani House',
    tagline: 'Centuries of Nizami Dum Cooking Heritage',
    cuisine: 'Hyderabadi · Lucknowi Dum Biryani · Kebabs',
    address: 'Banjara Hills, Road No. 12, Hyderabad, Telangana 500034',
    phone: '+91 40 2335 1122',
    openHours: '11:30 AM – 11:00 PM (Daily)',
    status: 'Open Now · Closes 11:00 PM',
    rating: 4.9,
    reviewCount: 2890,
    coverImage: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=1200&auto=format&fit=crop&q=80',
    logo: '👑',
    themeColor: '#0F5132',
    accentColor: '#E0A96D',
    tableDefault: 'Table 12',
    fssaiNumber: '22119988776655',
    wifiName: 'RoyalBiryani_WiFi',
    wifiPass: 'dumcooking2026'
  },
  'cafe-delight': {
    id: 'cafe-delight',
    name: 'Café Masala & Co.',
    tagline: 'Modern Indian Bistro & Artisanal Brews',
    cuisine: 'Modern Indian Tapas · Chai Bar · Fusion Desserts',
    address: 'Koregaon Park, Lane 6, Pune, Maharashtra 411001',
    phone: '+91 20 6601 4455',
    openHours: '09:00 AM – 10:30 PM (Daily)',
    status: 'Open Now · Closes 10:30 PM',
    rating: 4.7,
    reviewCount: 980,
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop&q=80',
    logo: '☕',
    themeColor: '#78350F',
    accentColor: '#F59E0B',
    tableDefault: 'Table 08',
    fssaiNumber: '33445566778899',
    wifiName: 'CafeMasala_Free',
    wifiPass: 'chaiandspice'
  }
};

export const CATEGORIES = [
  { id: 'all', name: 'All Dishes', icon: '✨', description: 'Browse complete kitchen selection' },
  { id: 'popular', name: 'Popular', icon: '⭐', description: 'Chef’s most-loved signature specialties' },
  { id: 'starters', name: 'Starters', icon: '🥗', description: 'Crispy chaats, tikkas & tandoor appetizers' },
  { id: 'main-course', name: 'Main Course', icon: '🍛', description: 'Rich velvet gravies & aromatic curries' },
  { id: 'rice-biryani', name: 'Rice & Biryani', icon: '🍚', description: 'Fragrant aged Basmati & slow-cooked dum biryani' },
  { id: 'breads', name: 'Breads', icon: '🫓', description: 'Fresh clay-oven tandoori rotis, naans & parathas' },
  { id: 'beverages', name: 'Beverages', icon: '🍹', description: 'Refreshing desi lassis, mocktails & cooler drinks' },
  { id: 'desserts', name: 'Desserts', icon: '🍰', description: 'Traditional mithais, slow-simmered rabdi & kulfi' }
];

export const MENU_ITEMS = [
  // --- STARTERS & TANDOOR ---
  {
    id: 'dish-1',
    name: 'Paneer Tikka Angaare',
    category: 'starters',
    price: 260,
    type: 'veg',
    spice: 'medium',
    flavour: '🔥 Smoky & Charred',
    popular: true,
    chefSpecial: true,
    description: 'Fresh farm malai cottage cheese cubes infused with Kashmiri deghi mirch, hung curd, and mustard oil, fire-roasted in clay tandoor with bell peppers.',
    image: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Malai Paneer', 'Hung Curd', 'Kashmiri Chili', 'Mustard Oil', 'Bell Peppers', 'Kasuri Methi', 'Chaat Masala'],
    allergens: ['Dairy', 'Mustard'],
    portion: '6 pieces (Serves 2)',
    calories: '340 kcal',
    prepTime: '15-18 mins'
  },
  {
    id: 'dish-2',
    name: 'Murgh Malai Tikka',
    category: 'starters',
    price: 340,
    type: 'non-veg',
    spice: 'mild',
    flavour: '🥛 Silken Cashew & Cream',
    popular: true,
    chefSpecial: false,
    description: 'Melt-in-mouth chicken tenderloins steeped overnight in royal cashew cream, cardamom, mild cheese, and fresh coriander, char-grilled over smoldering coals.',
    image: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Boneless Chicken Breast', 'Heavy Cream', 'Cashew Paste', 'Green Cardamom', 'Processed Cheese', 'White Pepper'],
    allergens: ['Dairy', 'Tree Nuts (Cashew)'],
    portion: '6 succulent pieces (Serves 2)',
    calories: '410 kcal',
    prepTime: '18-20 mins'
  },
  {
    id: 'dish-3',
    name: 'Dahi Ke Shahi Kebab',
    category: 'starters',
    price: 240,
    type: 'veg',
    spice: 'mild',
    flavour: '✨ Velvet Curd & Mint',
    popular: false,
    chefSpecial: true,
    description: 'Velvety golden patties prepared from hung yogurt, roasted gram flour, crushed green chilies, and fresh mint with a delicate crispy outer crust.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Hung Strained Curd', 'Roasted Besan', 'Finely Chopped Ginger', 'Green Chilies', 'Fresh Mint', 'Black Salt'],
    allergens: ['Dairy'],
    portion: '5 patties with Mint Chutney',
    calories: '280 kcal',
    prepTime: '12-15 mins'
  },
  {
    id: 'dish-4',
    name: 'Tandoori Chicken (Half / Full)',
    category: 'starters',
    price: 380,
    type: 'non-veg',
    spice: 'spicy',
    flavour: '🍗 Clay-Charred & Spicy',
    popular: true,
    chefSpecial: true,
    description: 'The undisputed Punjabi classic: tender whole spring chicken marinated with roasted spices, garlic, ginger, and spiced curd, roasted until smoky and crisp.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Spring Chicken on Bone', 'Deghi Red Chili', 'Ginger-Garlic Paste', 'Lemon Juice', 'Tandoori Garam Masala'],
    allergens: ['Dairy', 'Gluten-Free'],
    portion: 'Half Chicken (4 hearty cuts)',
    calories: '490 kcal',
    prepTime: '20-25 mins'
  },
  {
    id: 'dish-5',
    name: 'Crispy Kurkure Bhindi Chaat',
    category: 'starters',
    price: 210,
    type: 'veg',
    spice: 'medium',
    flavour: '🍋 Tangy Amchur Crunch',
    popular: false,
    chefSpecial: false,
    description: 'Julienned okra tossed in amchur (dry mango powder), roasted cumin, and carom seeds, flash-fried to an irresistible crunch and garnished with pomegranate.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Tender Ladyfingers (Bhindi)', 'Chickpea Flour', 'Amchur Powder', 'Ajwain Seeds', 'Pomegranate Pearls'],
    allergens: ['Vegan Friendly', 'Gluten-Free'],
    portion: 'Platter (Serves 2-3)',
    calories: '220 kcal',
    prepTime: '10-12 mins'
  },
  {
    id: 'dish-6',
    name: 'Bhatti Da Murgh Tikka',
    category: 'starters',
    price: 330,
    type: 'non-veg',
    spice: 'spicy',
    flavour: '🌶️ Peppercorn & Mustard Fire',
    popular: false,
    chefSpecial: false,
    description: 'Rustic Punjabi highway dhaba style chicken tikka marinated with whole crushed coriander seeds, black peppercorns, and mustard oil.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Boneless Chicken', 'Coarse Black Pepper', 'Dhaniya Seeds', 'Kachri Powder', 'Mustard Oil'],
    allergens: ['Mustard', 'Gluten-Free'],
    portion: '6 pieces',
    calories: '370 kcal',
    prepTime: '15-18 mins'
  },
  {
    id: 'dish-7',
    name: 'Hara Bhara Kebab',
    category: 'starters',
    price: 220,
    type: 'veg',
    spice: 'mild',
    flavour: '🌿 Spinach & Roasted Cumin',
    popular: true,
    chefSpecial: false,
    description: 'Pan-seared spinach, green peas, and mashed potato medallions topped with golden cashew halves, fragrant with roasted cumin and nutmeg.',
    image: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Fresh Baby Spinach', 'Green Peas', 'Potatoes', 'Cashews', 'Nutmeg', 'Coriander Root'],
    allergens: ['Tree Nuts (Cashew)', 'Vegan Friendly'],
    portion: '6 medallions',
    calories: '240 kcal',
    prepTime: '12-14 mins'
  },

  // --- MAIN COURSE & CURRIES ---
  {
    id: 'dish-8',
    name: 'Butter Chicken (Murgh Makhani)',
    category: 'main-course',
    price: 390,
    type: 'non-veg',
    spice: 'mild',
    flavour: '🧈 Velvet Makhani & Kasuri Methi',
    popular: true,
    chefSpecial: true,
    description: 'Tandoor-smoked chicken tikka simmered in a silken, slow-cooked tomato gravy finished with real butter, cashew paste, and hand-rubbed kasuri methi.',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Charred Chicken Tikka', 'San Marzano Tomatoes', 'Dairy Butter', 'Cashew Paste', 'Fenugreek Leaves', 'Honey'],
    allergens: ['Dairy', 'Tree Nuts (Cashew)'],
    portion: '450 ml (Serves 2)',
    calories: '560 kcal',
    prepTime: '15 mins'
  },
  {
    id: 'dish-9',
    name: 'Dal Makhani (Slow-Cooked 24 Hrs)',
    category: 'main-course',
    price: 290,
    type: 'veg',
    spice: 'mild',
    flavour: '🍲 Slow-Embers Smoky Cream',
    popular: true,
    chefSpecial: true,
    description: 'Signature whole black lentils (urad dal) and kidney beans simmered overnight over slow charcoal embers with cultured butter and fresh cream.',
    image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Black Urad Dal', 'Rajma Beans', 'Slow-Simmered Tomato Puree', 'Desi White Makhan', 'Fresh Heavy Cream'],
    allergens: ['Dairy', 'Gluten-Free'],
    portion: '450 ml (Serves 2-3)',
    calories: '420 kcal',
    prepTime: '10-12 mins'
  },
  {
    id: 'dish-10',
    name: 'Paneer Lababdar',
    category: 'main-course',
    price: 320,
    type: 'veg',
    spice: 'medium',
    flavour: '🍅 Spiced Tomato & Melon Seed',
    popular: true,
    chefSpecial: false,
    description: 'Cottage cheese chunks cooked in a textured onion-tomato gravy along with grated paneer, roasted melon seeds, and fragrant whole spices.',
    image: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Malai Paneer (cubes & grated)', 'Magaz (Melon Seeds)', 'Ripe Tomatoes', 'Kasoori Methi', 'Cardamom'],
    allergens: ['Dairy'],
    portion: '450 ml (Serves 2)',
    calories: '450 kcal',
    prepTime: '15 mins'
  },
  {
    id: 'dish-11',
    name: 'Kashmiri Mutton Rogan Josh',
    category: 'main-course',
    price: 490,
    type: 'non-veg',
    spice: 'medium',
    flavour: '🌿 Saffron, Saunf & Dry Ginger',
    popular: true,
    chefSpecial: true,
    description: 'Tender prime lamb cuts slow-braised in an aromatic broth infused with Kashmiri Ratan Jot bark, dried ginger (Saunth), fennel, and whole cloves.',
    image: 'https://images.unsplash.com/photo-1545247181-516773cae7be?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Prime Baby Goat / Mutton', 'Kashmiri Mirch', 'Fennel Powder (Saunf)', 'Dry Ginger', 'Asafoetida (Hing)'],
    allergens: ['Gluten-Free', 'Dairy-Free'],
    portion: '4 tender bone-in cuts (Serves 2)',
    calories: '520 kcal',
    prepTime: '18-20 mins'
  },
  {
    id: 'dish-12',
    name: 'Palak Paneer Lahsuni',
    category: 'main-course',
    price: 295,
    type: 'veg',
    spice: 'mild',
    flavour: '🧄 Burnt Golden Garlic & Spinach',
    popular: false,
    chefSpecial: false,
    description: 'Blanched smooth farm spinach puree tempered with burnt golden garlic, green chilies, and cumin, cradling soft cottage cheese cubes.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Fresh Spinach (Palak)', 'Paneer Cubes', 'Roasted Golden Garlic', 'Cumin Seeds', 'Ghee'],
    allergens: ['Dairy', 'Gluten-Free'],
    portion: '400 ml (Serves 2)',
    calories: '310 kcal',
    prepTime: '12-14 mins'
  },
  {
    id: 'dish-13',
    name: 'Chicken Tikka Masala',
    category: 'main-course',
    price: 380,
    type: 'non-veg',
    spice: 'spicy',
    flavour: '🌶️ Roasted Dhaniya & Pepper Masala',
    popular: true,
    chefSpecial: false,
    description: 'Spicy tandoori chicken tikka tossed with diced onions and bell peppers in a robust, semi-dry roasted spice masala gravy.',
    image: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Boneless Chicken Tikka', 'Capsicum & Diced Red Onion', 'Brown Onion Paste', 'Coriander Seeds', 'Garam Masala'],
    allergens: ['Dairy'],
    portion: '450 ml (Serves 2)',
    calories: '490 kcal',
    prepTime: '15 mins'
  },
  {
    id: 'dish-14',
    name: 'Shahi Malai Kofta',
    category: 'main-course',
    price: 330,
    type: 'veg',
    spice: 'mild',
    flavour: '👑 Royal Cashew & Khoya Sweet-Savory',
    popular: true,
    chefSpecial: true,
    description: 'Delicate dumplings of cottage cheese, khoya, and dried raisins served floating in a rich, sweet-savory white cashew-saffron gravy.',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Paneer & Mawa Kofta', 'Golden Sultanas', 'Cashew Cream Gravy', 'Kashmiri Saffron', 'Green Cardamom'],
    allergens: ['Dairy', 'Tree Nuts (Cashew)'],
    portion: '3 large koftas with gravy (Serves 2)',
    calories: '510 kcal',
    prepTime: '16-18 mins'
  },
  {
    id: 'dish-15',
    name: 'Yellow Dal Tadka Double Ghee',
    category: 'main-course',
    price: 220,
    type: 'veg',
    spice: 'medium',
    flavour: '🪔 Desi Ghee & Hing Tadka',
    popular: false,
    chefSpecial: false,
    description: 'Homestyle yellow arhar lentils boiled with turmeric, finished with a sizzling double tadka of pure cow ghee, whole red chilies, and garlic.',
    image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Toor Dal (Arhar)', 'Pure Cow Ghee', 'Garlic Pods', 'Whole Dried Byadgi Chillies', 'Hing'],
    allergens: ['Dairy (Ghee)', 'Gluten-Free'],
    portion: '400 ml (Serves 2)',
    calories: '260 kcal',
    prepTime: '10 mins'
  },

  // --- RICE & DUM BIRYANI ---
  {
    id: 'dish-16',
    name: 'Dum Gosht Mutton Biryani',
    category: 'rice-biryani',
    price: 480,
    type: 'non-veg',
    spice: 'medium',
    flavour: '👑 Aged Basmati, Kesar & Dum',
    popular: true,
    chefSpecial: true,
    description: 'Aged long-grain Basmati rice layered with succulent goat meat, saffron milk, caramelized birista onions, and mint, sealed with dough and slow dum-cooked in handi.',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Aged Daawat Basmati', 'Baby Mutton Cuts', 'Saffron (Kesar)', 'Caramelized Onions (Birista)', 'Desi Ghee', 'Kewra Water'],
    allergens: ['Dairy (Ghee)'],
    portion: 'Clay Handi with Burani Raita & Salan (Serves 2)',
    calories: '680 kcal',
    prepTime: '20 mins'
  },
  {
    id: 'dish-17',
    name: 'Murgh Hyderabadi Dum Biryani',
    category: 'rice-biryani',
    price: 390,
    type: 'non-veg',
    spice: 'spicy',
    flavour: '🔥 Potli Masala & Birista Handi',
    popular: true,
    chefSpecial: true,
    description: 'Fragrant Basmati rice cooked with bone-in marinated chicken cuts, secret potli masala, fresh mint leaves, and desi ghee. Served with spicy Mirchi Ka Salan.',
    image: 'https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Basmati Rice', 'Chicken Cuts', 'Mint & Coriander', 'Potli Garam Masala', 'Yogurt Marinade', 'Rose Essence'],
    allergens: ['Dairy', 'Gluten-Free'],
    portion: 'Handi (Serves 1-2) + Raita + Salan',
    calories: '610 kcal',
    prepTime: '18 mins'
  },
  {
    id: 'dish-18',
    name: 'Subz Shahi Veg Dum Biryani',
    category: 'rice-biryani',
    price: 310,
    type: 'veg',
    spice: 'medium',
    flavour: '🥕 Saffron Infused Farm Vegetables',
    popular: true,
    chefSpecial: false,
    description: 'Garden-fresh florets of cauliflower, carrots, beans, baby corn, and fresh cottage cheese cubes cooked in dum style with aromatic spices and saffron.',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Basmati Rice', 'Paneer Cubes', 'Farm Vegetables', 'Saffron Milk', 'Fried Cashews', 'Browned Onions'],
    allergens: ['Dairy', 'Tree Nuts (Cashew)'],
    portion: 'Handi (Serves 2) + Boondi Raita',
    calories: '460 kcal',
    prepTime: '15-18 mins'
  },
  {
    id: 'dish-19',
    name: 'Jeera Basmati Rice with Ghee',
    category: 'rice-biryani',
    price: 190,
    type: 'veg',
    spice: 'none',
    flavour: '🍚 Pure Ghee & Roasted Cumin',
    popular: false,
    chefSpecial: false,
    description: 'Fluffy steamed Basmati rice tempered in pure desi ghee with roasted whole cumin seeds and fresh coriander.',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Basmati Rice', 'Desi Ghee', 'Shahjeera / Cumin Seeds', 'Cilantro'],
    allergens: ['Dairy (Ghee)', 'Gluten-Free'],
    portion: '350g (Serves 2)',
    calories: '280 kcal',
    prepTime: '10 mins'
  },

  // --- BREADS & TANDOORI ---
  {
    id: 'dish-20',
    name: 'Garlic Butter Naan',
    category: 'breads',
    price: 85,
    type: 'veg',
    spice: 'none',
    flavour: '🧄 Toasted Garlic & Molten Butter',
    popular: true,
    chefSpecial: false,
    description: 'Refined flour flatbread slapped on the walls of clay tandoor, topped with minced roasted garlic, fresh cilantro, and generous brushed butter.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Maida Flour', 'Milk & Curd Dough', 'Chopped Garlic', 'Amul Butter', 'Coriander'],
    allergens: ['Gluten', 'Dairy'],
    portion: '1 large naan cut in half',
    calories: '190 kcal',
    prepTime: '5-8 mins'
  },
  {
    id: 'dish-21',
    name: 'Amritsari Stuffed Kulcha',
    category: 'breads',
    price: 130,
    type: 'veg',
    spice: 'mild',
    flavour: '🥔 Flaky Crisp & Spiced Aloo',
    popular: true,
    chefSpecial: true,
    description: 'Layered, flaky Punjabi flatbread stuffed with spiced potatoes, crushed coriander seeds, pomegranate powder, and onions, crushed with melting butter.',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Layered Dough', 'Spiced Mashed Potato', 'Anardana (Pomegranate)', 'Ajwain', 'White Butter'],
    allergens: ['Gluten', 'Dairy'],
    portion: '1 hearty kulcha + Chole dip',
    calories: '290 kcal',
    prepTime: '8-10 mins'
  },
  {
    id: 'dish-22',
    name: 'Tandoori Roti (Butter / Plain)',
    category: 'breads',
    price: 45,
    type: 'veg',
    spice: 'none',
    flavour: '🌾 Stone-Ground Wheat & Clay Char',
    popular: false,
    chefSpecial: false,
    description: 'Wholesome 100% stone-ground whole wheat flatbread baked crisp in clay oven.',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Whole Wheat Atta', 'Water', 'Ghee / Butter optional'],
    allergens: ['Gluten', 'Dairy optional'],
    portion: '1 piece',
    calories: '110 kcal',
    prepTime: '5 mins'
  },
  {
    id: 'dish-23',
    name: 'Chilli Cheese Naan',
    category: 'breads',
    price: 110,
    type: 'veg',
    spice: 'medium',
    flavour: '🧀 Molten Mozzarella & Green Chilli',
    popular: true,
    chefSpecial: false,
    description: 'Soft tandoori naan stuffed with molten mozzarella and cheddar cheese, topped with finely chopped spicy green chilies and nigella seeds.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Maida', 'Mozzarella & Processed Cheese', 'Bird-eye Green Chilies', 'Kalonji Seeds', 'Butter'],
    allergens: ['Gluten', 'Dairy'],
    portion: '1 stuffed naan (4 cuts)',
    calories: '270 kcal',
    prepTime: '6-8 mins'
  },

  // --- BEVERAGES & LASSI ---
  {
    id: 'dish-24',
    name: 'Alphonso Mango Lassi',
    category: 'beverages',
    price: 160,
    type: 'veg',
    spice: 'none',
    flavour: '🥭 Rich Alphonso & Cardamom',
    popular: true,
    chefSpecial: true,
    description: 'Thick, creamy yogurt churned with pure Ratnagiri Alphonso mango pulp, green cardamom, and garnished with slivered pistachios and saffron.',
    image: 'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Cultured Yogurt (Dahi)', 'Ratnagiri Alphonso Pulp', 'Cardamom', 'Pistachio Slivers', 'Saffron'],
    allergens: ['Dairy', 'Tree Nuts (Pistachio)'],
    portion: '350 ml Earthen Kulhad Glass',
    calories: '230 kcal',
    prepTime: '5 mins'
  },
  {
    id: 'dish-25',
    name: 'Masala Shahi Chaas (Spiced Buttermilk)',
    category: 'beverages',
    price: 90,
    type: 'veg',
    spice: 'mild',
    flavour: '🧂 Cooling Mint & Bhuna Jeera',
    popular: false,
    chefSpecial: false,
    description: 'Cooling churned curd infused with roasted cumin powder, black salt, grated ginger, fresh mint, and fresh green chili.',
    image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Buttermilk', 'Bhuna Jeera (Roasted Cumin)', 'Kala Namak', 'Mint Leaves', 'Curry Leaf Tempering'],
    allergens: ['Dairy', 'Gluten-Free'],
    portion: '300 ml Glass',
    calories: '65 kcal',
    prepTime: '3-5 mins'
  },
  {
    id: 'dish-26',
    name: 'Kashmiri Pink Noon Chai / Masala Chai',
    category: 'beverages',
    price: 80,
    type: 'veg',
    spice: 'mild',
    flavour: '☕ Cinnamon & Crushed Ginger Brew',
    popular: false,
    chefSpecial: false,
    description: 'Slow-brewed Assam CTC tea with crushed fresh ginger, green cardamom pods, cinnamon bark, and full-cream milk.',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Assam Black Tea', 'Fresh Ginger', 'Cardamom', 'Clove & Cinnamon', 'Boiled Milk'],
    allergens: ['Dairy'],
    portion: '200 ml Earthen Cup',
    calories: '110 kcal',
    prepTime: '5-7 mins'
  },
  {
    id: 'dish-27',
    name: 'Fresh Nimbu Shikanji Cooler',
    category: 'beverages',
    price: 110,
    type: 'veg',
    spice: 'none',
    flavour: '🍋 Sparking Lime & Rock Salt',
    popular: true,
    chefSpecial: false,
    description: 'Sparkling Delhi street style lemonade with freshly squeezed lime, rock salt, mint sprigs, and roasted cumin spice blend.',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Fresh Lime Juice', 'Rock Salt', 'Club Soda / Chilled Water', 'Mint Sprigs', 'Shikanji Masala'],
    allergens: ['Vegan Friendly', 'Gluten-Free'],
    portion: '350 ml Tall Glass',
    calories: '75 kcal',
    prepTime: '4 mins'
  },

  // --- DESSERTS & KULFI ---
  {
    id: 'dish-28',
    name: 'Shahi Gulab Jamun with Kesar Rabdi',
    category: 'desserts',
    price: 180,
    type: 'veg',
    spice: 'none',
    flavour: '🌹 Rose Nectar & Chilled Kesar Rabdi',
    popular: true,
    chefSpecial: true,
    description: 'Two hot, melt-in-mouth reduced milk dumplings soaked in rose-cardamom sugar syrup, served resting on a bed of chilled saffron rabdi.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Khoya / Mawa', 'Rosewater Sugar Syrup', 'Slow-Simmered Rabdi Milk', 'Saffron Strands', 'Almond Slivers'],
    allergens: ['Dairy', 'Tree Nuts (Almond)', 'Gluten'],
    portion: '2 warm pieces + Rabdi (Serves 2)',
    calories: '380 kcal',
    prepTime: '5 mins'
  },
  {
    id: 'dish-29',
    name: 'Matka Kesar Pista Kulfi',
    category: 'desserts',
    price: 160,
    type: 'veg',
    spice: 'none',
    flavour: '🍨 Slow-Reduced Kesar & Pistachio',
    popular: true,
    chefSpecial: true,
    description: 'Traditional slow-reduced full-fat milk ice cream frozen in miniature clay pots, enriched with Kashmiri saffron, green cardamom, and crushed pistachios.',
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Slow-Evaporated Rabdi Milk', 'Kesar (Saffron)', 'Irani Pistachios', 'Green Cardamom'],
    allergens: ['Dairy', 'Tree Nuts (Pistachio)'],
    portion: '1 Clay Pot (Matka)',
    calories: '240 kcal',
    prepTime: 'Ready to serve'
  },
  {
    id: 'dish-30',
    name: 'Royal Shahi Tukda with Silver Vark',
    category: 'desserts',
    price: 190,
    type: 'veg',
    spice: 'none',
    flavour: '👑 Ghee-Crisped Brioche & Cardamom Rabdi',
    popular: false,
    chefSpecial: true,
    description: 'Nawabi dessert of crisp ghee-fried brioche steeped in saffron sugar syrup, blanketed with thick cardamom rabdi and decorated with edible silver leaf.',
    image: 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=800&auto=format&fit=crop&q=80',
    ingredients: ['Artisanal Bread', 'Pure Desi Ghee', 'Saffron Sugar Nectar', 'Reduced Rabdi Cream', 'Edible Silver Foil (Vark)'],
    allergens: ['Dairy', 'Gluten', 'Tree Nuts (Almond & Cashew)'],
    portion: '2 generous slices (Serves 2)',
    calories: '420 kcal',
    prepTime: '6-8 mins'
  }
];
